info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-08T04:07:25.033Z"}
info: Connected to the database. {"timestamp":"2022-03-08T04:07:25.146Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-08T04:17:23.382Z"}
info: Connected to the database. {"timestamp":"2022-03-08T04:17:23.447Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-08T04:28:09.194Z"}
info: Connected to the database. {"timestamp":"2022-03-08T04:28:09.275Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-08T04:28:28.536Z"}
info: Connected to the database. {"timestamp":"2022-03-08T04:28:28.608Z"}
error: 
    status - 500 
    message - ReferenceError: compare is not defined
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:16:22)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-08T04:29:10.556Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-08T04:31:20.066Z"}
info: Connected to the database. {"timestamp":"2022-03-08T04:31:20.137Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-08T04:31:55.790Z"}
info: Connected to the database. {"timestamp":"2022-03-08T04:31:55.859Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-08T04:37:15.118Z"}
info: Connected to the database. {"timestamp":"2022-03-08T04:37:15.187Z"}
error: 
    status - 500 
    message - ReferenceError: find is not defined
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:21:11)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-08T04:37:29.913Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-08T04:44:53.951Z"}
info: Connected to the database. {"timestamp":"2022-03-08T04:44:54.035Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-08T04:45:55.082Z"}
info: Connected to the database. {"timestamp":"2022-03-08T04:45:55.157Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-08T04:46:50.573Z"}
info: Connected to the database. {"timestamp":"2022-03-08T04:46:50.643Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-08T04:47:52.630Z"}
info: Connected to the database. {"timestamp":"2022-03-08T04:47:52.707Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-08T04:49:57.232Z"}
info: Connected to the database. {"timestamp":"2022-03-08T04:49:57.301Z"}
error: 
    status - 500 
    message - Error: not a valid password
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:26:13)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-08T04:50:01.716Z"}
error: 
    status - 500 
    message - ReferenceError: email is not defined
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:24:14)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-08T04:50:19.467Z"}
error: 
    status - 500 
    message - ReferenceError: email is not defined
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:24:14)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-08T04:51:55.449Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-08T04:54:28.844Z"}
info: Connected to the database. {"timestamp":"2022-03-08T04:54:28.916Z"}
error: 
    status - 500 
    message - Error: not a valid password
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:26:13)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-08T04:54:46.083Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-08T04:55:32.480Z"}
info: Connected to the database. {"timestamp":"2022-03-08T04:55:32.553Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-08T06:06:07.050Z"}
info: Connected to the database. {"timestamp":"2022-03-08T06:06:07.144Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-09T03:21:13.692Z"}
info: Connected to the database. {"timestamp":"2022-03-09T03:21:13.778Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: FundooNotes.users index: email_1 dup key: { email: "neeraja12@gmail.com" } 
      url - /api/v1/users/register 
      method - POST 
      IP - ::ffff:127.0.0.1
     {"timestamp":"2022-03-09T03:21:23.616Z"}
error: 
    status - 500 
    message - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 11000
    at ServerResponse.writeHead (_http_server.js:259:11)
    at ServerResponse.writeHead (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:250:8)
    at write_ (_http_outgoing.js:711:9)
    at ServerResponse.end (_http_outgoing.js:825:5)
    at ServerResponse.send (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\response.js:267:15)
    at appErrorHandler (C:\Users\HP\Documents\Node-projects\fundoonote\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\router\index.js:321:13) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-09T03:21:23.649Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-09T05:23:58.233Z"}
info: Connected to the database. {"timestamp":"2022-03-09T05:23:58.275Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T06:16:51.037Z"}
info: Connected to the database. {"timestamp":"2022-03-10T06:16:51.134Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: FundooNotes.users index: email_1 dup key: { email: "neeraja123@gmail.com" } 
      url - /api/v1/users/register 
      method - POST 
      IP - ::ffff:127.0.0.1
     {"timestamp":"2022-03-10T06:18:17.931Z"}
error: 
    status - 500 
    message - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 11000
    at ServerResponse.writeHead (_http_server.js:259:11)
    at ServerResponse.writeHead (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:250:8)
    at write_ (_http_outgoing.js:711:9)
    at ServerResponse.end (_http_outgoing.js:825:5)
    at ServerResponse.send (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\response.js:267:15)
    at appErrorHandler (C:\Users\HP\Documents\Node-projects\fundoonote\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\router\index.js:321:13) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T06:18:17.960Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T06:20:21.796Z"}
info: Connected to the database. {"timestamp":"2022-03-10T06:20:21.898Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T06:20:37.903Z"}
info: Connected to the database. {"timestamp":"2022-03-10T06:20:37.954Z"}
error: 
    status - 500 
    message - Error: user already exists
    at _callee2$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:16:11)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T06:20:43.955Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T06:22:50.118Z"}
info: Connected to the database. {"timestamp":"2022-03-10T06:22:50.164Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T06:23:53.752Z"}
info: Connected to the database. {"timestamp":"2022-03-10T06:23:53.790Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T06:26:57.447Z"}
info: Connected to the database. {"timestamp":"2022-03-10T06:26:57.491Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T09:38:52.293Z"}
info: Connected to the database. {"timestamp":"2022-03-10T09:38:52.336Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T09:40:10.210Z"}
info: Connected to the database. {"timestamp":"2022-03-10T09:40:10.280Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T09:44:08.933Z"}
info: Connected to the database. {"timestamp":"2022-03-10T09:44:08.993Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T09:46:47.032Z"}
info: Connected to the database. {"timestamp":"2022-03-10T09:46:47.076Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T09:48:12.640Z"}
info: Connected to the database. {"timestamp":"2022-03-10T09:48:12.685Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T09:48:35.878Z"}
info: Connected to the database. {"timestamp":"2022-03-10T09:48:35.925Z"}
error: uncaughtException: Router.use() requires a middleware function but got a Object
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\router\index.js:464:13)
    at routes (C:\Users\HP\Documents\Node-projects\fundoonote\src\routes\/index.js:16:10)
    at Object.<anonymous> (C:\Users\HP\Documents\Node-projects\fundoonote\src\/index.js:32:32)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module._compile (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.newLoader [as .js] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\pirates\lib\index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:937:32) {"date":"Thu Mar 10 2022 15:21:06 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1716660},"process":{"argv":["node","C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\index.js"],"cwd":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18376017,"external":20611732,"heapTotal":82124800,"heapUsed":41523024,"rss":114270208},"pid":11212,"uid":null,"version":"v14.17.5"},"stack":"TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\express\\lib\\router\\index.js:464:13)\n    at routes (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\routes\\/index.js:16:10)\n    at Object.<anonymous> (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\/index.js:32:32)\n    at Module._compile (internal/modules/cjs/loader.js:1072:14)\n    at Module._compile (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)\n    at Object.newLoader [as .js] (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (internal/modules/cjs/loader.js:937:32)","timestamp":"2022-03-10T09:51:06.392Z","trace":[{"column":13,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\express\\lib\\router\\index.js","function":"Function.use","line":464,"method":"use","native":false},{"column":10,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\routes\\/index.js","function":"routes","line":16,"method":null,"native":false},{"column":32,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\/index.js","function":null,"line":32,"method":null,"native":false},{"column":14,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":1072,"method":"_compile","native":false},{"column":24,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":136,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":1101,"method":".js","native":false},{"column":7,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":141,"method":"js]","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":937,"method":"load","native":false}]}
error: uncaughtException: Router.use() requires a middleware function but got a Object
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\router\index.js:464:13)
    at routes (C:\Users\HP\Documents\Node-projects\fundoonote\src\routes\/index.js:16:10)
    at Object.<anonymous> (C:\Users\HP\Documents\Node-projects\fundoonote\src\/index.js:32:32)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module._compile (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.newLoader [as .js] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\pirates\lib\index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:937:32) {"date":"Thu Mar 10 2022 15:36:44 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1717598},"process":{"argv":["node","C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\index.js"],"cwd":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18357060,"external":20592775,"heapTotal":81862656,"heapUsed":39661208,"rss":113864704},"pid":11900,"uid":null,"version":"v14.17.5"},"stack":"TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\express\\lib\\router\\index.js:464:13)\n    at routes (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\routes\\/index.js:16:10)\n    at Object.<anonymous> (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\/index.js:32:32)\n    at Module._compile (internal/modules/cjs/loader.js:1072:14)\n    at Module._compile (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)\n    at Object.newLoader [as .js] (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (internal/modules/cjs/loader.js:937:32)","timestamp":"2022-03-10T10:06:44.648Z","trace":[{"column":13,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\express\\lib\\router\\index.js","function":"Function.use","line":464,"method":"use","native":false},{"column":10,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\routes\\/index.js","function":"routes","line":16,"method":null,"native":false},{"column":32,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\/index.js","function":null,"line":32,"method":null,"native":false},{"column":14,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":1072,"method":"_compile","native":false},{"column":24,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":136,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":1101,"method":".js","native":false},{"column":7,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":141,"method":"js]","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":937,"method":"load","native":false}]}
error: uncaughtException: Router.use() requires a middleware function but got a Object
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\router\index.js:464:13)
    at routes (C:\Users\HP\Documents\Node-projects\fundoonote\src\routes\/index.js:16:10)
    at Object.<anonymous> (C:\Users\HP\Documents\Node-projects\fundoonote\src\/index.js:32:32)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module._compile (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.newLoader [as .js] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\pirates\lib\index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:937:32) {"date":"Thu Mar 10 2022 15:37:53 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1717667},"process":{"argv":["node","C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\index.js"],"cwd":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18346128,"external":20581843,"heapTotal":82915328,"heapUsed":50014024,"rss":115740672},"pid":6712,"uid":null,"version":"v14.17.5"},"stack":"TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\express\\lib\\router\\index.js:464:13)\n    at routes (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\routes\\/index.js:16:10)\n    at Object.<anonymous> (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\/index.js:32:32)\n    at Module._compile (internal/modules/cjs/loader.js:1072:14)\n    at Module._compile (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)\n    at Object.newLoader [as .js] (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (internal/modules/cjs/loader.js:937:32)","timestamp":"2022-03-10T10:07:53.585Z","trace":[{"column":13,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\express\\lib\\router\\index.js","function":"Function.use","line":464,"method":"use","native":false},{"column":10,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\routes\\/index.js","function":"routes","line":16,"method":null,"native":false},{"column":32,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\/index.js","function":null,"line":32,"method":null,"native":false},{"column":14,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":1072,"method":"_compile","native":false},{"column":24,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":136,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":1101,"method":".js","native":false},{"column":7,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":141,"method":"js]","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":937,"method":"load","native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T10:08:29.763Z"}
info: Connected to the database. {"timestamp":"2022-03-10T10:08:29.807Z"}
error: 
    status - 500 
    message - Error: user does not exist
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:29:11)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T10:16:08.510Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:31:36)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T10:18:04.267Z"}
error: 
    status - 500 
    message - Error: not a valid password
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:38:13)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T10:18:27.400Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T10:21:21.089Z"}
info: Connected to the database. {"timestamp":"2022-03-10T10:21:21.140Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T10:27:20.424Z"}
info: Connected to the database. {"timestamp":"2022-03-10T10:27:20.481Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt must be provided
    at Object.verify (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\jsonwebtoken\verify.js:53:17)
    at _callee$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\middlewares\/auth.middleware.js:22:32)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12 
    url - /api/v1/notes 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T10:27:43.181Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt must be provided
    at Object.verify (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\jsonwebtoken\verify.js:53:17)
    at _callee$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\middlewares\/auth.middleware.js:22:32)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12 
    url - /api/v1/notes 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T10:28:04.588Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt must be provided
    at Object.verify (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\jsonwebtoken\verify.js:53:17)
    at _callee$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\middlewares\/auth.middleware.js:22:32)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12 
    url - /api/v1/notes 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T10:28:11.233Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T10:29:00.919Z"}
info: Connected to the database. {"timestamp":"2022-03-10T10:29:00.963Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt must be provided
    at Object.verify (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\jsonwebtoken\verify.js:53:17)
    at _callee$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\middlewares\/auth.middleware.js:22:32)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12 
    url - /api/v1/notes 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T10:29:03.349Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T10:29:49.421Z"}
info: Connected to the database. {"timestamp":"2022-03-10T10:29:49.468Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T16:04:58.322Z"}
info: Connected to the database. {"timestamp":"2022-03-10T16:04:58.362Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/notes.services.js:8:43)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getAllNotes (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/notes.services.js:7:25) 
    url - /api/v1/notes 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T16:05:09.711Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-10T16:06:07.461Z"}
info: Connected to the database. {"timestamp":"2022-03-10T16:06:07.502Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-11T06:08:43.202Z"}
info: Connected to the database. {"timestamp":"2022-03-11T06:08:43.273Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-11T06:50:37.025Z"}
info: Connected to the database. {"timestamp":"2022-03-11T06:50:37.079Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-11T06:51:30.539Z"}
info: Connected to the database. {"timestamp":"2022-03-11T06:51:30.588Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-11T06:53:26.714Z"}
info: Connected to the database. {"timestamp":"2022-03-11T06:53:26.843Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-11T06:54:38.736Z"}
info: Connected to the database. {"timestamp":"2022-03-11T06:54:38.844Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-11T06:55:16.899Z"}
info: Connected to the database. {"timestamp":"2022-03-11T06:55:16.943Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-12T03:49:04.604Z"}
info: Connected to the database. {"timestamp":"2022-03-12T03:49:04.672Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-12T03:51:46.907Z"}
info: Connected to the database. {"timestamp":"2022-03-12T03:51:46.945Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-12T05:43:54.493Z"}
info: Connected to the database. {"timestamp":"2022-03-12T05:43:54.533Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-12T05:45:21.668Z"}
info: Connected to the database. {"timestamp":"2022-03-12T05:45:21.705Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-12T05:49:38.509Z"}
info: Connected to the database. {"timestamp":"2022-03-12T05:49:38.547Z"}
error: 
    status - 500 
    message - ReferenceError: req is not defined
    at _callee4$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/notes.services.js:30:46)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.deleteNote (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/notes.services.js:28:24) 
    url - /api/v1/notes/6229cf083e863a3700004a7f 
    method - DELETE 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-12T05:49:50.777Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-12T05:51:17.002Z"}
info: Connected to the database. {"timestamp":"2022-03-12T05:51:17.034Z"}
error: 
    status - 500 
    message - Error: Cast to undefined failed for value undefined at path "undefined"
    at new MongooseError (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\error\mongooseError.js:7:1)
    at new CastError (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\error\cast.js:31:7)
    at model.Query.exec (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/notes/6229cf083e863a3700004a7f 
    method - DELETE 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-12T05:51:35.835Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-12T05:53:39.105Z"}
info: Connected to the database. {"timestamp":"2022-03-12T05:53:39.140Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-12T05:56:31.130Z"}
info: Connected to the database. {"timestamp":"2022-03-12T05:56:31.171Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-12T05:57:04.781Z"}
info: Connected to the database. {"timestamp":"2022-03-12T05:57:04.817Z"}
error: 
    status - 500 
    message - Error: Cast to undefined failed for value undefined at path "undefined"
    at new MongooseError (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\error\mongooseError.js:7:1)
    at new CastError (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\error\cast.js:31:7)
    at model.Query.exec (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/notes/6229cf083e863a3700004a7f 
    method - DELETE 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-12T05:57:09.381Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-12T05:58:44.412Z"}
info: Connected to the database. {"timestamp":"2022-03-12T05:58:44.450Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-12T06:18:46.132Z"}
info: Connected to the database. {"timestamp":"2022-03-12T06:18:46.194Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-12T06:19:01.295Z"}
info: Connected to the database. {"timestamp":"2022-03-12T06:19:01.334Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-12T06:19:40.266Z"}
info: Connected to the database. {"timestamp":"2022-03-12T06:19:40.342Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-12T06:19:50.700Z"}
info: Connected to the database. {"timestamp":"2022-03-12T06:19:50.757Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-12T06:21:48.480Z"}
info: Connected to the database. {"timestamp":"2022-03-12T06:21:48.537Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-12T06:21:57.360Z"}
info: Connected to the database. {"timestamp":"2022-03-12T06:21:57.414Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T04:29:13.626Z"}
info: Connected to the database. {"timestamp":"2022-03-14T04:29:13.705Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T04:37:08.750Z"}
info: Connected to the database. {"timestamp":"2022-03-14T04:37:08.784Z"}
error: 
    status - 500 
    message - TypeError: NotesService.getNote is not a function
    at _callee5$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\controllers\/note.controller.js:64:37)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at getNote (C:\Users\HP\Documents\Node-projects\fundoonote\src\controllers\/note.controller.js:62:21) 
    url - /api/v1/notes/6229d24dc16fca50886df9de 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-14T04:42:08.774Z"}
error: 
    status - 500 
    message - TypeError: NotesService.getNote is not a function
    at _callee5$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\controllers\/note.controller.js:64:37)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at getNote (C:\Users\HP\Documents\Node-projects\fundoonote\src\controllers\/note.controller.js:62:21) 
    url - /api/v1/notes/6229d24dc16fca50886df9de 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-14T04:43:31.654Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T04:47:56.974Z"}
info: Connected to the database. {"timestamp":"2022-03-14T04:47:57.011Z"}
error: 
    status - 500 
    message - Error: not a valid password
    at _callee2$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:34:13)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-14T06:18:11.485Z"}
error: 
    status - 500 
    message - Error: not a valid password
    at _callee2$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:34:13)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-14T06:18:30.732Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:19:23.481Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:19:23.528Z"}
error: 
    status - 500 
    message - Error: not a valid password
    at _callee2$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:34:13)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-14T06:19:51.872Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:21:08.304Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:21:08.359Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:23:36.487Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:23:36.530Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:24:46.336Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:24:46.397Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:25:20.779Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:25:20.826Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:26:33.922Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:26:33.971Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:28:33.158Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:28:33.231Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:29:25.598Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:29:25.657Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:29:44.900Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:29:44.945Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:30:46.735Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:30:46.787Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:31:17.820Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:31:17.888Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:34:33.620Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:34:33.692Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:35:37.676Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:35:37.717Z"}
error: 
    status - 500 
    message - Error: Parameter "filter" to find() must be an object, got 622edda47c4e554ac8ed347f
    at new MongooseError (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\error\mongooseError.js:7:1)
    at new ObjectParameterError (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\error\objectParameter.js:20:5)
    at model.Query.Query.find (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\query.js:2098:16)
    at Function.find (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\model.js:2157:13)
    at _callee$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/notes.services.js:10:28)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21) 
    url - /api/v1/notes 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-14T06:35:45.456Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:36:19.224Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:36:19.268Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:37:32.868Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:37:32.905Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:40:34.487Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:40:34.530Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:40:44.316Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:40:44.381Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:41:43.941Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:41:43.989Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:42:06.540Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:42:06.579Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:43:38.281Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:43:38.329Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-03-14T06:43:44.754Z"}
info: Connected to the database. {"timestamp":"2022-03-14T06:43:44.809Z"}
