error: 
    status - 500 
    message - ReferenceError: compare is not defined
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:16:22)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-08T04:29:10.556Z"}
error: 
    status - 500 
    message - ReferenceError: find is not defined
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:21:11)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-08T04:37:29.913Z"}
error: 
    status - 500 
    message - Error: not a valid password
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:26:13)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-08T04:50:01.716Z"}
error: 
    status - 500 
    message - ReferenceError: email is not defined
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:24:14)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-08T04:50:19.467Z"}
error: 
    status - 500 
    message - ReferenceError: email is not defined
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:24:14)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-08T04:51:55.449Z"}
error: 
    status - 500 
    message - Error: not a valid password
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:26:13)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-08T04:54:46.083Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: FundooNotes.users index: email_1 dup key: { email: "neeraja12@gmail.com" } 
      url - /api/v1/users/register 
      method - POST 
      IP - ::ffff:127.0.0.1
     {"timestamp":"2022-03-09T03:21:23.616Z"}
error: 
    status - 500 
    message - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 11000
    at ServerResponse.writeHead (_http_server.js:259:11)
    at ServerResponse.writeHead (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:250:8)
    at write_ (_http_outgoing.js:711:9)
    at ServerResponse.end (_http_outgoing.js:825:5)
    at ServerResponse.send (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\response.js:267:15)
    at appErrorHandler (C:\Users\HP\Documents\Node-projects\fundoonote\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\router\index.js:321:13) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-09T03:21:23.649Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: FundooNotes.users index: email_1 dup key: { email: "neeraja123@gmail.com" } 
      url - /api/v1/users/register 
      method - POST 
      IP - ::ffff:127.0.0.1
     {"timestamp":"2022-03-10T06:18:17.931Z"}
error: 
    status - 500 
    message - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 11000
    at ServerResponse.writeHead (_http_server.js:259:11)
    at ServerResponse.writeHead (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:250:8)
    at write_ (_http_outgoing.js:711:9)
    at ServerResponse.end (_http_outgoing.js:825:5)
    at ServerResponse.send (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\response.js:267:15)
    at appErrorHandler (C:\Users\HP\Documents\Node-projects\fundoonote\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\router\index.js:321:13) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T06:18:17.960Z"}
error: 
    status - 500 
    message - Error: user already exists
    at _callee2$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:16:11)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T06:20:43.955Z"}
error: uncaughtException: Router.use() requires a middleware function but got a Object
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\router\index.js:464:13)
    at routes (C:\Users\HP\Documents\Node-projects\fundoonote\src\routes\/index.js:16:10)
    at Object.<anonymous> (C:\Users\HP\Documents\Node-projects\fundoonote\src\/index.js:32:32)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module._compile (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.newLoader [as .js] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\pirates\lib\index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:937:32) {"date":"Thu Mar 10 2022 15:21:06 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1716660},"process":{"argv":["node","C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\index.js"],"cwd":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18376017,"external":20611732,"heapTotal":82124800,"heapUsed":41523024,"rss":114270208},"pid":11212,"uid":null,"version":"v14.17.5"},"stack":"TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\express\\lib\\router\\index.js:464:13)\n    at routes (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\routes\\/index.js:16:10)\n    at Object.<anonymous> (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\/index.js:32:32)\n    at Module._compile (internal/modules/cjs/loader.js:1072:14)\n    at Module._compile (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)\n    at Object.newLoader [as .js] (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (internal/modules/cjs/loader.js:937:32)","timestamp":"2022-03-10T09:51:06.392Z","trace":[{"column":13,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\express\\lib\\router\\index.js","function":"Function.use","line":464,"method":"use","native":false},{"column":10,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\routes\\/index.js","function":"routes","line":16,"method":null,"native":false},{"column":32,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\/index.js","function":null,"line":32,"method":null,"native":false},{"column":14,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":1072,"method":"_compile","native":false},{"column":24,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":136,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":1101,"method":".js","native":false},{"column":7,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":141,"method":"js]","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":937,"method":"load","native":false}]}
error: uncaughtException: Router.use() requires a middleware function but got a Object
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\router\index.js:464:13)
    at routes (C:\Users\HP\Documents\Node-projects\fundoonote\src\routes\/index.js:16:10)
    at Object.<anonymous> (C:\Users\HP\Documents\Node-projects\fundoonote\src\/index.js:32:32)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module._compile (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.newLoader [as .js] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\pirates\lib\index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:937:32) {"date":"Thu Mar 10 2022 15:36:44 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1717598},"process":{"argv":["node","C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\index.js"],"cwd":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18357060,"external":20592775,"heapTotal":81862656,"heapUsed":39661208,"rss":113864704},"pid":11900,"uid":null,"version":"v14.17.5"},"stack":"TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\express\\lib\\router\\index.js:464:13)\n    at routes (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\routes\\/index.js:16:10)\n    at Object.<anonymous> (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\/index.js:32:32)\n    at Module._compile (internal/modules/cjs/loader.js:1072:14)\n    at Module._compile (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)\n    at Object.newLoader [as .js] (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (internal/modules/cjs/loader.js:937:32)","timestamp":"2022-03-10T10:06:44.648Z","trace":[{"column":13,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\express\\lib\\router\\index.js","function":"Function.use","line":464,"method":"use","native":false},{"column":10,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\routes\\/index.js","function":"routes","line":16,"method":null,"native":false},{"column":32,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\/index.js","function":null,"line":32,"method":null,"native":false},{"column":14,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":1072,"method":"_compile","native":false},{"column":24,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":136,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":1101,"method":".js","native":false},{"column":7,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":141,"method":"js]","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":937,"method":"load","native":false}]}
error: uncaughtException: Router.use() requires a middleware function but got a Object
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\express\lib\router\index.js:464:13)
    at routes (C:\Users\HP\Documents\Node-projects\fundoonote\src\routes\/index.js:16:10)
    at Object.<anonymous> (C:\Users\HP\Documents\Node-projects\fundoonote\src\/index.js:32:32)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module._compile (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.newLoader [as .js] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\pirates\lib\index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:937:32) {"date":"Thu Mar 10 2022 15:37:53 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1717667},"process":{"argv":["node","C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\index.js"],"cwd":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18346128,"external":20581843,"heapTotal":82915328,"heapUsed":50014024,"rss":115740672},"pid":6712,"uid":null,"version":"v14.17.5"},"stack":"TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\express\\lib\\router\\index.js:464:13)\n    at routes (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\routes\\/index.js:16:10)\n    at Object.<anonymous> (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\/index.js:32:32)\n    at Module._compile (internal/modules/cjs/loader.js:1072:14)\n    at Module._compile (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)\n    at Object.newLoader [as .js] (C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (internal/modules/cjs/loader.js:937:32)","timestamp":"2022-03-10T10:07:53.585Z","trace":[{"column":13,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\express\\lib\\router\\index.js","function":"Function.use","line":464,"method":"use","native":false},{"column":10,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\routes\\/index.js","function":"routes","line":16,"method":null,"native":false},{"column":32,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\src\\/index.js","function":null,"line":32,"method":null,"native":false},{"column":14,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":1072,"method":"_compile","native":false},{"column":24,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":136,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":1101,"method":".js","native":false},{"column":7,"file":"C:\\Users\\HP\\Documents\\Node-projects\\fundoonote\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":141,"method":"js]","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":937,"method":"load","native":false}]}
error: 
    status - 500 
    message - Error: user does not exist
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:29:11)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T10:16:08.510Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:31:36)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T10:18:04.267Z"}
error: 
    status - 500 
    message - Error: not a valid password
    at _callee3$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:38:13)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T10:18:27.400Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt must be provided
    at Object.verify (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\jsonwebtoken\verify.js:53:17)
    at _callee$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\middlewares\/auth.middleware.js:22:32)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12 
    url - /api/v1/notes 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T10:27:43.181Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt must be provided
    at Object.verify (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\jsonwebtoken\verify.js:53:17)
    at _callee$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\middlewares\/auth.middleware.js:22:32)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12 
    url - /api/v1/notes 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T10:28:04.588Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt must be provided
    at Object.verify (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\jsonwebtoken\verify.js:53:17)
    at _callee$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\middlewares\/auth.middleware.js:22:32)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12 
    url - /api/v1/notes 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T10:28:11.233Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt must be provided
    at Object.verify (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\jsonwebtoken\verify.js:53:17)
    at _callee$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\middlewares\/auth.middleware.js:22:32)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12 
    url - /api/v1/notes 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T10:29:03.349Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/notes.services.js:8:43)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getAllNotes (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/notes.services.js:7:25) 
    url - /api/v1/notes 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-10T16:05:09.711Z"}
error: 
    status - 500 
    message - ReferenceError: req is not defined
    at _callee4$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/notes.services.js:30:46)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.deleteNote (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/notes.services.js:28:24) 
    url - /api/v1/notes/6229cf083e863a3700004a7f 
    method - DELETE 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-12T05:49:50.777Z"}
error: 
    status - 500 
    message - Error: Cast to undefined failed for value undefined at path "undefined"
    at new MongooseError (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\error\mongooseError.js:7:1)
    at new CastError (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\error\cast.js:31:7)
    at model.Query.exec (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/notes/6229cf083e863a3700004a7f 
    method - DELETE 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-12T05:51:35.835Z"}
error: 
    status - 500 
    message - Error: Cast to undefined failed for value undefined at path "undefined"
    at new MongooseError (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\error\mongooseError.js:7:1)
    at new CastError (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\error\cast.js:31:7)
    at model.Query.exec (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/notes/6229cf083e863a3700004a7f 
    method - DELETE 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-12T05:57:09.381Z"}
error: 
    status - 500 
    message - TypeError: NotesService.getNote is not a function
    at _callee5$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\controllers\/note.controller.js:64:37)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at getNote (C:\Users\HP\Documents\Node-projects\fundoonote\src\controllers\/note.controller.js:62:21) 
    url - /api/v1/notes/6229d24dc16fca50886df9de 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-14T04:42:08.774Z"}
error: 
    status - 500 
    message - TypeError: NotesService.getNote is not a function
    at _callee5$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\controllers\/note.controller.js:64:37)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at getNote (C:\Users\HP\Documents\Node-projects\fundoonote\src\controllers\/note.controller.js:62:21) 
    url - /api/v1/notes/6229d24dc16fca50886df9de 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-14T04:43:31.654Z"}
error: 
    status - 500 
    message - Error: not a valid password
    at _callee2$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:34:13)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-14T06:18:11.485Z"}
error: 
    status - 500 
    message - Error: not a valid password
    at _callee2$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:34:13)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-14T06:18:30.732Z"}
error: 
    status - 500 
    message - Error: not a valid password
    at _callee2$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/user.service.js:34:13)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-14T06:19:51.872Z"}
error: 
    status - 500 
    message - Error: Parameter "filter" to find() must be an object, got 622edda47c4e554ac8ed347f
    at new MongooseError (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\error\mongooseError.js:7:1)
    at new ObjectParameterError (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\error\objectParameter.js:20:5)
    at model.Query.Query.find (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\query.js:2098:16)
    at Function.find (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\mongoose\lib\model.js:2157:13)
    at _callee$ (C:\Users\HP\Documents\Node-projects\fundoonote\src\services\/notes.services.js:10:28)
    at tryCatch (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\HP\Documents\Node-projects\fundoonote\node_modules\regenerator-runtime\runtime.js:119:21) 
    url - /api/v1/notes 
    method - GET 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-14T06:35:45.456Z"}
